const audio = document.getElementById("audio");
const title = document.getElementById("title");
const artist = document.getElementById("artist");
const cover = document.getElementById("cover");
const playBtn = document.getElementById("play");
const prevBtn = document.getElementById("prev");
const nextBtn = document.getElementById("next");
const seekBackBtn = document.getElementById("seekBack");
const seekForwardBtn = document.getElementById("seekForward");
const progress = document.getElementById("progress");
const currentTimeEl = document.getElementById("currentTime");
const durationEl = document.getElementById("duration");
const volume = document.getElementById("volume");
const shuffleBtn = document.getElementById("shuffle");
const repeatBtn = document.getElementById("repeat");
const listToggleBtn = document.getElementById("listToggle");
const trackListPanel = document.getElementById("trackListPanel");
const trackListEl = document.getElementById("trackList");
const trackSearch = document.getElementById("trackSearch");
const addTrackBtn = document.getElementById("addTrackBtn");
const addTrackInput = document.getElementById("addTrackInput");
const eqToggleBtn = document.getElementById("eqToggle");
const eqPanel = document.getElementById("eqPanel");
const eqSliders = document.querySelectorAll(".eq-slider");
const eqResetBtn = document.getElementById("eqReset");
const visualizerCanvas = document.getElementById("visualizer");
const vizCtx = visualizerCanvas.getContext("2d");

// Web Audio API state (created lazily on first playback,
// since browsers require a user gesture before audio can start)
let audioCtx = null;
let sourceNode = null;
let eqFilters = [];
let analyser = null;
let vizDataArray = null;
let vizAnimationId = null;
const EQ_BANDS = [60, 170, 350, 1000, 3500, 10000];

// --- IndexedDB storage for tracks added via the UI ---
// (these live in the browser, separate from songs/playlist.json,
// so tracks you add here persist across reloads without touching the terminal)
const DB_NAME = "musicPlayerDB";
const DB_VERSION = 1;
const STORE_NAME = "customTracks";

function openTracksDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: "id", autoIncrement: true });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function saveCustomTrack(file, name, artistName) {
  const db = await openTracksDB();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    const req = store.add({ name, artist: artistName, blob: file, addedAt: Date.now() });
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function getAllCustomTracks() {
  const db = await openTracksDB();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readonly");
    const store = tx.objectStore(STORE_NAME);
    const req = store.getAll();
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function deleteCustomTrack(id) {
  const db = await openTracksDB();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    const req = store.delete(id);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

// Best-effort "Artist - Title" parsing from a picked filename
function guessTitleArtist(filename) {
  let name = filename.replace(/\.[^/.]+$/, ""); // strip extension
  name = name.replace(/_+/g, " ").trim();
  const parts = name.split(/\s+-\s+/);
  if (parts.length === 2 && parts[0].length < 40) {
    return { artistName: parts[0].trim(), trackName: parts[1].trim() };
  }
  return { artistName: "Unknown Artist", trackName: name };
}

// Songs are loaded from songs/playlist.json, which is generated by
// running: python3 build_playlist.py
// (that script copies your mp3s from ~/Music into songs/ and writes
// the json file automatically based on what it finds)
let songs = [];
let songIndex = 0;
let isPlaying = false;

// Shuffle state
let isShuffle = false;
let shuffleOrder = [];
let shufflePos = 0;

// Repeat state: "off" -> "all" -> "one" -> "off" ...
let repeatMode = "off";

async function loadPlaylist() {
  try {
    const res = await fetch("songs/playlist.json");
    songs = await res.json();
  } catch (err) {
    console.warn("Could not load songs/playlist.json, using fallback song list.", err);
    songs = [
      { name: "Song Title 1", artist: "Artist 1", src: "songs/song1.mp3", cover: "images/cover.jpg" }
    ];
  }

  // Append any tracks previously added through the "+ Add" button
  try {
    const customTracks = await getAllCustomTracks();
    customTracks.forEach(t => {
      songs.push({
        name: t.name,
        artist: t.artist,
        src: URL.createObjectURL(t.blob),
        cover: "images/cover.jpg",
        isCustom: true,
        dbId: t.id
      });
    });
  } catch (err) {
    console.warn("Could not load tracks added via the UI:", err);
  }

  renderTrackList();
  loadSong(songIndex);
}

function loadSong(index) {
  if (!songs.length) return;
  const song = songs[index];
  title.textContent = song.name;
  artist.textContent = song.artist;
  cover.src = song.cover;
  audio.src = song.src;
  progress.value = 0;
  currentTimeEl.textContent = "0:00";
  updateProgressFill(0);
  highlightActiveTrack();
}

function initAudioGraph() {
  if (audioCtx) return; // already set up, only do this once per page load
  try {
    audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    sourceNode = audioCtx.createMediaElementSource(audio);

    eqFilters = EQ_BANDS.map(freq => {
      const filter = audioCtx.createBiquadFilter();
      filter.type = "peaking";
      filter.frequency.value = freq;
      filter.Q.value = 1;
      filter.gain.value = 0;
      return filter;
    });

    analyser = audioCtx.createAnalyser();
    analyser.fftSize = 64;
    vizDataArray = new Uint8Array(analyser.frequencyBinCount);

    // Chain: source -> filter1 -> filter2 -> ... -> analyser -> speakers
    let node = sourceNode;
    eqFilters.forEach(f => { node.connect(f); node = f; });
    node.connect(analyser);
    analyser.connect(audioCtx.destination);

    drawVisualizer();
  } catch (err) {
    console.warn("Web Audio EQ/visualizer unavailable in this browser:", err);
  }
}

function playSong() {
  initAudioGraph();
  if (audioCtx && audioCtx.state === "suspended") {
    audioCtx.resume();
  }
  const playPromise = audio.play();
  if (playPromise && playPromise.catch) {
    playPromise.catch(err => {
      console.error("Playback failed:", err);
      alert("This track couldn't be played. The file format may not be supported by your browser.");
    });
  }
  playBtn.innerHTML = "&#10074;&#10074;"; // pause icon ||
  isPlaying = true;
}

function pauseSong() {
  audio.pause();
  playBtn.innerHTML = "&#9658;"; // play icon ▶
  isPlaying = false;
}

function generateShuffleOrder() {
  shuffleOrder = songs.map((_, i) => i);
  // Fisher-Yates shuffle
  for (let i = shuffleOrder.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffleOrder[i], shuffleOrder[j]] = [shuffleOrder[j], shuffleOrder[i]];
  }
  // Keep the currently playing song as the shuffle "starting point"
  // so toggling shuffle mid-playback doesn't jump elsewhere.
  const curPos = shuffleOrder.indexOf(songIndex);
  [shuffleOrder[0], shuffleOrder[curPos]] = [shuffleOrder[curPos], shuffleOrder[0]];
  shufflePos = 0;
}

function nextSong() {
  if (isShuffle) {
    shufflePos = (shufflePos + 1) % shuffleOrder.length;
    songIndex = shuffleOrder[shufflePos];
  } else {
    songIndex = (songIndex + 1) % songs.length;
  }
  loadSong(songIndex);
  playSong();
}

function prevSong() {
  if (isShuffle) {
    shufflePos = (shufflePos - 1 + shuffleOrder.length) % shuffleOrder.length;
    songIndex = shuffleOrder[shufflePos];
  } else {
    songIndex = (songIndex - 1 + songs.length) % songs.length;
  }
  loadSong(songIndex);
  playSong();
}

function playTrackAt(index) {
  songIndex = index;
  if (isShuffle) {
    // realign shuffle position so next/prev continue sensibly from here
    const pos = shuffleOrder.indexOf(index);
    shufflePos = pos === -1 ? 0 : pos;
  }
  loadSong(songIndex);
  playSong();
}

function formatTime(seconds) {
  if (isNaN(seconds)) return "0:00";
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60).toString().padStart(2, "0");
  return `${mins}:${secs}`;
}

function fillRange(rangeEl, percent) {
  const p = Math.min(Math.max(percent, 0), 100);
  rangeEl.style.background =
    `linear-gradient(to right, #6a3de8 0%, #6a3de8 ${p}%, #33343d ${p}%, #33343d 100%)`;
}

function seekBy(seconds) {
  if (!audio.duration) return;
  audio.currentTime = Math.min(
    Math.max(audio.currentTime + seconds, 0),
    audio.duration
  );
}

// --- Shuffle button ---
shuffleBtn.addEventListener("click", () => {
  isShuffle = !isShuffle;
  shuffleBtn.classList.toggle("active", isShuffle);
  shuffleBtn.innerHTML = isShuffle ? "🔀 Shuffle: On" : "🔀 Shuffle";
  if (isShuffle) generateShuffleOrder();
  renderTrackList(trackSearch.value);
});

// --- Repeat button (cycles off -> all -> one) ---
function updateRepeatBtn() {
  repeatBtn.classList.toggle("active", repeatMode !== "off");
  const icon = repeatMode === "one" ? "🔂" : "🔁";
  const label = repeatMode === "off" ? "Off" : repeatMode === "all" ? "All" : "One";
  repeatBtn.innerHTML = `${icon} Repeat: ${label}`;
  repeatBtn.title = `Repeat: ${label}`;
}

repeatBtn.addEventListener("click", () => {
  repeatMode = repeatMode === "off" ? "all" : repeatMode === "all" ? "one" : "off";
  updateRepeatBtn();
});

// --- Equalizer panel ---
eqToggleBtn.addEventListener("click", () => {
  eqPanel.classList.toggle("hidden");
  eqToggleBtn.classList.toggle("active");
});

eqSliders.forEach(slider => {
  const valueLabel = slider.nextElementSibling; // .eq-value span right after the slider

  slider.addEventListener("input", () => {
    const freq = Number(slider.dataset.freq);
    const filter = eqFilters.find(f => f.frequency.value === freq);
    if (filter) filter.gain.value = Number(slider.value);
    const val = Number(slider.value);
    valueLabel.textContent = val > 0 ? `+${val}` : `${val}`;
  });
});

eqResetBtn.addEventListener("click", () => {
  eqSliders.forEach(slider => {
    slider.value = 0;
    slider.dispatchEvent(new Event("input"));
  });
});

// --- Frequency visualizer (draws while audio plays) ---
function drawVisualizer() {
  vizAnimationId = requestAnimationFrame(drawVisualizer);
  if (!analyser) return;

  analyser.getByteFrequencyData(vizDataArray);

  const w = visualizerCanvas.width;
  const h = visualizerCanvas.height;
  vizCtx.clearRect(0, 0, w, h);

  const barCount = vizDataArray.length;
  const barWidth = w / barCount;

  for (let i = 0; i < barCount; i++) {
    const barHeight = (vizDataArray[i] / 255) * h;
    vizCtx.fillStyle = "#6a3de8";
    vizCtx.fillRect(i * barWidth, h - barHeight, barWidth - 2, barHeight);
  }
}

// --- Track list panel ---
function renderTrackList(filter = "") {
  trackListEl.innerHTML = "";
  const lowerFilter = filter.trim().toLowerCase();

  // When shuffle is on, show songs in the actual shuffled play order.
  // Otherwise show them in original playlist order.
  const order =
    isShuffle && shuffleOrder.length === songs.length
      ? shuffleOrder
      : songs.map((_, i) => i);

  order.forEach(i => {
    const song = songs[i];
    const matches =
      !lowerFilter ||
      song.name.toLowerCase().includes(lowerFilter) ||
      song.artist.toLowerCase().includes(lowerFilter);
    if (!matches) return;

    const li = document.createElement("li");
    li.dataset.index = i;
    if (i === songIndex) li.classList.add("active");

    const info = document.createElement("div");
    info.className = "track-info";

    const nameSpan = document.createElement("span");
    nameSpan.textContent = song.name;
    const artistSpan = document.createElement("span");
    artistSpan.className = "track-artist";
    artistSpan.textContent = song.artist;

    info.appendChild(nameSpan);
    info.appendChild(artistSpan);
    li.appendChild(info);

    if (song.isCustom) {
      const delBtn = document.createElement("button");
      delBtn.className = "track-delete-btn";
      delBtn.textContent = "×";
      delBtn.title = "Remove this track";
      delBtn.addEventListener("click", (ev) => {
        ev.stopPropagation();
        removeCustomTrack(i);
      });
      li.appendChild(delBtn);
    }

    li.addEventListener("click", () => playTrackAt(i));
    trackListEl.appendChild(li);
  });
}

function updateProgressFill(percent) {
  const p = Math.min(Math.max(percent, 0), 100);
  progress.style.background =
    `linear-gradient(to right, #6a3de8 ${p}%, #33343d ${p}%)`;
}

async function removeCustomTrack(index) {
  const song = songs[index];
  if (!song || !song.isCustom) return;

  try {
    await deleteCustomTrack(song.dbId);
  } catch (err) {
    console.warn("Failed to delete track from storage:", err);
  }

  songs.splice(index, 1);

  if (songIndex === index) {
    // The track being removed is the one currently loaded/playing
    pauseSong();
    songIndex = Math.min(songIndex, songs.length - 1);
    if (songs.length) loadSong(songIndex);
  } else if (songIndex > index) {
    songIndex -= 1;
  }

  if (isShuffle) generateShuffleOrder();
  renderTrackList(trackSearch.value);
}

function highlightActiveTrack() {
  [...trackListEl.children].forEach(li => {
    li.classList.toggle("active", Number(li.dataset.index) === songIndex);
  });
}

listToggleBtn.addEventListener("click", () => {
  trackListPanel.classList.toggle("hidden");
  listToggleBtn.classList.toggle("active");
});

trackSearch.addEventListener("input", () => {
  renderTrackList(trackSearch.value);
});

// --- Add tracks from your device ---
addTrackBtn.addEventListener("click", () => addTrackInput.click());

addTrackInput.addEventListener("change", async (e) => {
  const files = Array.from(e.target.files);

  for (const file of files) {
    const { trackName, artistName } = guessTitleArtist(file.name);
    try {
      const id = await saveCustomTrack(file, trackName, artistName);
      songs.push({
        name: trackName,
        artist: artistName,
        src: URL.createObjectURL(file),
        cover: "images/cover.jpg",
        isCustom: true,
        dbId: id
      });
    } catch (err) {
      console.warn("Failed to save track:", file.name, err);
    }
  }

  if (isShuffle) generateShuffleOrder();
  renderTrackList(trackSearch.value);

  // Reset so selecting the same file again still triggers "change"
  e.target.value = "";
});

// --- Core playback event wiring ---
playBtn.addEventListener("click", () => {
  isPlaying ? pauseSong() : playSong();
});

nextBtn.addEventListener("click", nextSong);
prevBtn.addEventListener("click", prevSong);
seekForwardBtn.addEventListener("click", () => seekBy(10));
seekBackBtn.addEventListener("click", () => seekBy(-10));

// --- Keyboard shortcut: spacebar toggles play/pause ---
document.addEventListener("keydown", (e) => {
  if (e.code !== "Space") return;

  const tag = document.activeElement.tagName;
  const isTypingOrScrubbing =
    tag === "INPUT" || tag === "TEXTAREA" || document.activeElement.isContentEditable;

  if (isTypingOrScrubbing) return; // let space work normally in search box / sliders

  e.preventDefault(); // stop the page itself from scrolling
  isPlaying ? pauseSong() : playSong();
});

audio.addEventListener("loadedmetadata", () => {
  durationEl.textContent = formatTime(audio.duration);
});

audio.addEventListener("error", () => {
  const song = songs[songIndex];
  console.error("Audio error on track:", song ? song.name : "(unknown)", audio.error);
  pauseSong();
  alert(
    `"${song ? song.name : "This track"}" couldn't be played. ` +
    `The file format may not be supported by your browser, or the file may be corrupted.`
  );
});

audio.addEventListener("timeupdate", () => {
  if (audio.duration) {
    const percent = (audio.currentTime / audio.duration) * 100;
    progress.value = percent;
    currentTimeEl.textContent = formatTime(audio.currentTime);
    updateProgressFill(percent);
  }
});

audio.addEventListener("ended", () => {
  if (repeatMode === "one") {
    audio.currentTime = 0;
    playSong();
    return;
  }

  const atEnd = isShuffle
    ? shufflePos === shuffleOrder.length - 1
    : songIndex === songs.length - 1;

  if (atEnd && repeatMode === "off") {
    pauseSong();
    audio.currentTime = 0;
    return;
  }

  nextSong();
});

progress.addEventListener("input", () => {
  updateProgressFill(progress.value);
  if (audio.duration) {
    audio.currentTime = (progress.value / 100) * audio.duration;
  }
});

volume.addEventListener("input", () => {
  audio.volume = volume.value;
});

// Kick things off by fetching the generated playlist
loadPlaylist();
updateRepeatBtn();
