const audio = document.getElementById("audio");
const title = document.getElementById("title");
const artist = document.getElementById("artist");
const cover = document.getElementById("cover");
const playBtn = document.getElementById("play");
const prevBtn = document.getElementById("prev");
const nextBtn = document.getElementById("next");
const seekBackBtn = document.getElementById("seekBack");
const seekForwardBtn = document.getElementById("seekForward");
const progress = document.getElementById("progress");
const currentTimeEl = document.getElementById("currentTime");
const durationEl = document.getElementById("duration");
const volume = document.getElementById("volume");
const shuffleBtn = document.getElementById("shuffle");
const repeatBtn = document.getElementById("repeat");
const listToggleBtn = document.getElementById("listToggle");
const trackListPanel = document.getElementById("trackListPanel");
const trackListEl = document.getElementById("trackList");
const trackSearch = document.getElementById("trackSearch");

// Songs are loaded from songs/playlist.json, which is generated by
// running: python3 build_playlist.py
// (that script copies your mp3s from ~/Music into songs/ and writes
// the json file automatically based on what it finds)
let songs = [];
let songIndex = 0;
let isPlaying = false;

// Shuffle state
let isShuffle = false;
let shuffleOrder = [];
let shufflePos = 0;

// Repeat state: "off" -> "all" -> "one" -> "off" ...
let repeatMode = "off";

async function loadPlaylist() {
  try {
    const res = await fetch("songs/playlist.json");
    songs = await res.json();
  } catch (err) {
    console.warn("Could not load songs/playlist.json, using fallback song list.", err);
    songs = [
      { name: "Song Title 1", artist: "Artist 1", src: "songs/song1.mp3", cover: "images/cover.jpg" }
    ];
  }
  renderTrackList();
  loadSong(songIndex);
}

function loadSong(index) {
  if (!songs.length) return;
  const song = songs[index];
  title.textContent = song.name;
  artist.textContent = song.artist;
  cover.src = song.cover;
  audio.src = song.src;
  progress.value = 0;
  currentTimeEl.textContent = "0:00";
  updateProgressFill(0);
  highlightActiveTrack();
}

function playSong() {
  audio.play();
  playBtn.innerHTML = "&#10074;&#10074;"; // pause icon ||
  isPlaying = true;
}

function pauseSong() {
  audio.pause();
  playBtn.innerHTML = "&#9658;"; // play icon ▶
  isPlaying = false;
}

function generateShuffleOrder() {
  shuffleOrder = songs.map((_, i) => i);
  // Fisher-Yates shuffle
  for (let i = shuffleOrder.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffleOrder[i], shuffleOrder[j]] = [shuffleOrder[j], shuffleOrder[i]];
  }
  // Keep the currently playing song as the shuffle "starting point"
  // so toggling shuffle mid-playback doesn't jump elsewhere.
  const curPos = shuffleOrder.indexOf(songIndex);
  [shuffleOrder[0], shuffleOrder[curPos]] = [shuffleOrder[curPos], shuffleOrder[0]];
  shufflePos = 0;
}

function nextSong() {
  if (isShuffle) {
    shufflePos = (shufflePos + 1) % shuffleOrder.length;
    songIndex = shuffleOrder[shufflePos];
  } else {
    songIndex = (songIndex + 1) % songs.length;
  }
  loadSong(songIndex);
  playSong();
}

function prevSong() {
  if (isShuffle) {
    shufflePos = (shufflePos - 1 + shuffleOrder.length) % shuffleOrder.length;
    songIndex = shuffleOrder[shufflePos];
  } else {
    songIndex = (songIndex - 1 + songs.length) % songs.length;
  }
  loadSong(songIndex);
  playSong();
}

function playTrackAt(index) {
  songIndex = index;
  if (isShuffle) {
    // realign shuffle position so next/prev continue sensibly from here
    const pos = shuffleOrder.indexOf(index);
    shufflePos = pos === -1 ? 0 : pos;
  }
  loadSong(songIndex);
  playSong();
}

function formatTime(seconds) {
  if (isNaN(seconds)) return "0:00";
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60).toString().padStart(2, "0");
  return `${mins}:${secs}`;
}

function fillRange(rangeEl, percent) {
  const p = Math.min(Math.max(percent, 0), 100);
  rangeEl.style.background =
    `linear-gradient(to right, #6a3de8 0%, #6a3de8 ${p}%, #33343d ${p}%, #33343d 100%)`;
}

function seekBy(seconds) {
  if (!audio.duration) return;
  audio.currentTime = Math.min(
    Math.max(audio.currentTime + seconds, 0),
    audio.duration
  );
}

// --- Shuffle button ---
shuffleBtn.addEventListener("click", () => {
  isShuffle = !isShuffle;
  shuffleBtn.classList.toggle("active", isShuffle);
  shuffleBtn.innerHTML = isShuffle ? "🔀 Shuffle: On" : "🔀 Shuffle";
  if (isShuffle) generateShuffleOrder();
});

// --- Repeat button (cycles off -> all -> one) ---
function updateRepeatBtn() {
  repeatBtn.classList.toggle("active", repeatMode !== "off");
  const icon = repeatMode === "one" ? "🔂" : "🔁";
  const label = repeatMode === "off" ? "Off" : repeatMode === "all" ? "All" : "One";
  repeatBtn.innerHTML = `${icon} Repeat: ${label}`;
  repeatBtn.title = `Repeat: ${label}`;
}

repeatBtn.addEventListener("click", () => {
  repeatMode = repeatMode === "off" ? "all" : repeatMode === "all" ? "one" : "off";
  updateRepeatBtn();
});

// --- Track list panel ---
function renderTrackList(filter = "") {
  trackListEl.innerHTML = "";
  const lowerFilter = filter.trim().toLowerCase();

  songs.forEach((song, i) => {
    const matches =
      !lowerFilter ||
      song.name.toLowerCase().includes(lowerFilter) ||
      song.artist.toLowerCase().includes(lowerFilter);
    if (!matches) return;

    const li = document.createElement("li");
    li.dataset.index = i;
    if (i === songIndex) li.classList.add("active");

    const nameSpan = document.createElement("span");
    nameSpan.textContent = song.name;
    const artistSpan = document.createElement("span");
    artistSpan.className = "track-artist";
    artistSpan.textContent = song.artist;

    li.appendChild(nameSpan);
    li.appendChild(artistSpan);
    li.addEventListener("click", () => playTrackAt(i));
    trackListEl.appendChild(li);
  });
}

function updateProgressFill(percent) {
  const p = Math.min(Math.max(percent, 0), 100);
  progress.style.background =
    `linear-gradient(to right, #6a3de8 ${p}%, #33343d ${p}%)`;
}

function highlightActiveTrack() {
  [...trackListEl.children].forEach(li => {
    li.classList.toggle("active", Number(li.dataset.index) === songIndex);
  });
}

listToggleBtn.addEventListener("click", () => {
  trackListPanel.classList.toggle("hidden");
  listToggleBtn.classList.toggle("active");
});

trackSearch.addEventListener("input", () => {
  renderTrackList(trackSearch.value);
});

// --- Core playback event wiring ---
playBtn.addEventListener("click", () => {
  isPlaying ? pauseSong() : playSong();
});

nextBtn.addEventListener("click", nextSong);
prevBtn.addEventListener("click", prevSong);
seekForwardBtn.addEventListener("click", () => seekBy(10));
seekBackBtn.addEventListener("click", () => seekBy(-10));

audio.addEventListener("loadedmetadata", () => {
  durationEl.textContent = formatTime(audio.duration);
});

audio.addEventListener("timeupdate", () => {
  if (audio.duration) {
    const percent = (audio.currentTime / audio.duration) * 100;
    progress.value = percent;
    currentTimeEl.textContent = formatTime(audio.currentTime);
    updateProgressFill(percent);
  }
});

audio.addEventListener("ended", () => {
  if (repeatMode === "one") {
    audio.currentTime = 0;
    playSong();
    return;
  }

  const atEnd = isShuffle
    ? shufflePos === shuffleOrder.length - 1
    : songIndex === songs.length - 1;

  if (atEnd && repeatMode === "off") {
    pauseSong();
    audio.currentTime = 0;
    return;
  }

  nextSong();
});

progress.addEventListener("input", () => {
  updateProgressFill(progress.value);
  if (audio.duration) {
    audio.currentTime = (progress.value / 100) * audio.duration;
  }
});

volume.addEventListener("input", () => {
  audio.volume = volume.value;
});

// Kick things off by fetching the generated playlist
loadPlaylist();
updateRepeatBtn();
